language: node_js
node_js:
   - 0.6


services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/dashboard
  - npm install kanso -g
  - npm install nodeunit -g


script: "kanso install; kanso push http://localhost:5984/dashboard"

after_script:
  # setup and run tests
  # deploy to a qa server
  - kanso push http://travis:XX0Y13CNL8M@reupholster.iriscouch.com/dashboard


notifications:
  email:
    - ryan.ramage@gmail.com
