language: node_js
node_js:
   - 0.10

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/dashboard
  - npm install kanso -g
  - npm install nodeunit -g

script: ./scripts/ci/run_build.sh

after_success:
  - ./scripts/ci/after_success.sh

notifications:
  email:
    - ryan.ramage@gmail.com
    - dev@medicmobile.org
