language: node_js
node_js:
   - 0.6


services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/dashboard
  - npm install kanso -g
  - npm install nodeunit -g


script: "kanso install; kanso push http://localhost:5984/dashboard"

after_script:
  - sudo ls /var/lib/couchdb
  - sudo cp /var/lib/couchdb/1.3.0/dashboard.couch ./static/dashboard.couch
  - sudo chown travis ./static/dashboard.couch
  - kanso push http://travis:XX0Y13CNL8M@reupholster.iriscouch.com/dashboard

notifications:
  email:
    - ryan.ramage@gmail.com
